/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WildlifeHeroes;

import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;

import java.util.HashMap;
import java.util.Map;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) {
        staticFileLocation("/public");
        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "layout.hbs");
        }, new HandlebarsTemplateEngine());
        get("/Animal", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "Animal.hbs");
        }, new HandlebarsTemplateEngine());
        get("/Rangers", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "Rangers.hbs");
        }, new HandlebarsTemplateEngine());
        get("/AnimalForm", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "AnimalForm.hbs");
        }, new HandlebarsTemplateEngine());
        get("/EndangeredAnimalForm", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "EndangeredAnimalForm.hbs");
        }, new HandlebarsTemplateEngine());
        get("/RangerForm", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "RangerForm.hbs");
        }, new HandlebarsTemplateEngine());
        post("/Animal", (request, respones) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            String speciesName = request.queryParams("species_name");
            request.session().attribute("species_name", speciesName);
            model.put("species_name", speciesName);
            String location = request.queryParams("Spotted_At");
            request.session().attribute("Spotted_At", location);
            model.put("Spotted_At", location);

            return new ModelAndView(model, Animal.hbs);
        }, new HandlebarsTemplateEngine());
    }
}
